### ISSUE TITLE
Add support for WebStorm 2023.2

### ISSUE THREAD

**Issue by tukusejssirs** [ilumer/Jetbrains-Text-Pastry#1]
Thanks for creating the plugin!

Could you add support for WebStorm 2023.2 (and other IDEs made by JetBrains) please? :pray:

**Comment by ilumer** [comment]
Okay, I will release a new version later today that supports WebStorm 2023.2.

**Comment by ilumer** [comment]
Thank you for your patience. I have released a new version to support JetBrains IDE 2023.2. You can download the codebase to build a JAR file for usage, or wait for it to be available for download after marketpace review.
Thank you for using, If you have any feedback or suggestions, please feel free to let us know.
<img width="900" alt="image" src="https://github.com/ilumer/Jetbrains-Text-Pastry/assets/10941253/2812743b-bfa4-43f2-b6de-4b0e2cfd9dbc">

**Comment by tukusejssirs** [comment]
I’ll await for it to be available in the marketplace. Thanks! :pray:

**Comment by ilumer** [comment]
@tukusejssirs the plugin is available in the marketplace ,i close this issue。

**Comment by tukusejssirs** [comment]
Hey, @ilumer! Could you add support for `2023.3.1` please? :pray:

**Comment by ilumer** [comment]
> Hey, @ilumer! Could you add support for `2023.3.1` please? 🙏

I  will apply this change tomorrow

**Comment by ilumer** [comment]
I spent some time dealing with the version issue of until-build. The plugin supporting version 232 will soon be available on the app market. @tukusejssirs
